detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    enabled: true
    max_statements: 20

  InstanceVariableAssumption:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  Attribute:
    enabled: false

directories:
  "app/helpers":
    FeatureEnvy:
      enabled: false

exclude_paths:
  - app/dashboards
