Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'app/dashboards/**/*'
