version: "3.3"

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local

services:
  db:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - .:/code
      - postgres-data:/var/lib/postgresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: P4Ssw0rD!
  
  test: &app
    image: integrador/makers:development
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bin/dev-entrypoint
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    working_dir: /code
    tty: false
    stdin_open: true
    depends_on:
      - db
    command: rspec
    environment: &app_environment
      DATABASE_URL: ${TEST_DB_URL:-""}
      LC_ALL: C.UTF-8
      RAILS_ENV: ${TEST_RAILS_ENV}
      RACK_ENV: ${TEST_RACK_ENV}
      RAILS_LOG_TO_STDOUT: "true"

  web:
    <<: *app
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - ${MAKERS_WEB_PORT:-3000}:3000
    environment:
      <<: *app_environment
      DATABASE_URL: ${DEV_DB_URL:-""}
      RAILS_ENV: ${DEV_RAILS_ENV}
      RACK_ENV: ${DEV_RACK_ENV}
    depends_on:
      - db
