# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  username: bayt
  password: 
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: makers

